[package]
name = "esphomeapi-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
esphomeapi = { path = "../esphomeapi" }
napi = { version = "3.0.0-alpha", features = ["tokio_rt"] }
napi-derive = "3.0.0-alpha"

[build-dependencies]
napi-build = "2.1.5"
