/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Light {
  get key(): number
  get name(): string
  get isOn(): boolean
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  toggle(): Promise<void>
  get brightness(): number
  get colorMode(): ColorMode
  get colorBrightness(): number
  get rgb(): [number, number, number]
  get white(): number
  get colorTemperature(): number
  get coldWhite(): number
  get warmWhite(): number
  get effect(): string
  sendCommand(options: LightCommandOptions): Promise<void>
}

export declare class Manager {
  static connect(options: ConnectionOptions): Promise<Manager>
  getDeviceName(): string
  getDeviceMac(): string
  getEntities(): Array<Entity>
  getSwitch(key: number): Switch
  getLight(key: number): Light
}

export declare class Switch {
  get key(): number
  get name(): string
  get isOn(): boolean
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  toggle(): Promise<void>
  setState(state: boolean): Promise<void>
}

export declare const enum ColorMode {
  Unknown = 0,
  OnOff = 1,
  Brightness = 2,
  White = 7,
  ColorTemperature = 11,
  ColdWarmWhite = 19,
  RGB = 35,
  RGBWhite = 39,
  RGBColorTemperature = 47,
  RGBColdWarmWhite = 51
}

export interface ConnectionOptions {
  address: string
  port: number
  password?: string
  expectedName?: string
  psk?: string
  clientInfo?: string
  keepAliveDuration?: number
}

export declare function discover(seconds: number): Promise<Array<ServiceInfo>>

export type Entity =
  | { type: 'Light', field0: number }
  | { type: 'Switch', field0: number }
  | { type: 'Sensor', field0: number }

export interface EntityInfo {
  key: number
  name: string
  uniqueId: string
  objectId: string
  deviceClass: string
  disabledByDefault: boolean
  entityCategory: string
  icon: string
}

/**
 * Initialize the logger with a console-like object.
 * The object must have `debug`, `info`, `warn`, and `error` methods.
 *
 * Example:
 * ```javascript
 * initLogger(console);
 * ```
 */
export declare function initLogger(console: Pick<Console, 'log' | 'warn' | 'error' | 'info' | 'debug' | 'trace'>): void

export interface LightCommandOptions {
  state?: boolean
  brightness?: number
  colorMode?: ColorMode
  colorBrightness?: number
  rgb?: [number, number, number]
  white?: number
  colorTemperature?: number
  coldWhite?: number
  warmWhite?: number
  transitionLength?: number
  flashLength?: number
  effect?: string
}

export interface ServiceInfo {
  tyDomain: string
  subDomain?: string
  fullname: string
  server: string
  addresses: Array<string>
  port: number
  hostTtl: number
  otherTtl: number
  priority: number
  weight: number
}
