/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Light {
  get key(): number
  get name(): string
  get isOn(): boolean
  get brightness(): number
  get colorMode(): ColorMode
  get colorBrightness(): number
  get rgb(): [number, number, number]
  get white(): number
  get colorTemperature(): number
  get coldWhite(): number
  get warmWhite(): number
  get effect(): string
  /**
   * Register a callback that is called whenever the light state changes.
   *
   * The callback receives a `LightState` object with all current state values.
   */
  onStateChange(callback: (state: LightState) => void): void
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  toggle(): Promise<void>
  sendCommand(options: LightCommandOptions): Promise<void>
}

export declare class Manager {
  static connect(options: ConnectionOptions): Promise<Manager>
  getDeviceName(): string
  getDeviceMac(): string
  getEntities(): Array<Light | Switch>
}

export declare class Switch {
  get key(): number
  get name(): string
  get isOn(): boolean
  /**
   * Register a callback that is called whenever the switch state changes.
   *
   * The callback receives a single boolean argument indicating whether the switch is on.
   */
  onStateChange(callback: (isOn: boolean) => void): void
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  toggle(): Promise<void>
  setState(state: boolean): Promise<void>
}

export declare const enum ColorMode {
  Unknown = 0,
  OnOff = 1,
  LegacyBrightness = 2,
  Brightness = 3,
  White = 7,
  ColorTemperature = 11,
  ColdWarmWhite = 19,
  RGB = 35,
  RGBWhite = 39,
  RGBColorTemperature = 47,
  RGBColdWarmWhite = 51
}

export interface ConnectionOptions {
  address: string
  port: number
  password?: string
  expectedName?: string
  psk?: string
  clientInfo?: string
  keepAliveDuration?: number
}

export declare function discover(seconds: number): Promise<Array<ServiceInfo>>

/**
 * Initialize the logger with a console-like object.
 * The object must have `debug`, `info`, `warn`, `error` and `trace` methods.
 *
 * Example:
 * ```javascript
 * initLogger(console);
 * ```
 */
export declare function initLogger(console: Pick<Console, 'warn' | 'error' | 'info' | 'debug' | 'trace'>): void

export interface LightCommandOptions {
  state?: boolean
  brightness?: number
  colorMode?: ColorMode
  colorBrightness?: number
  rgb?: [number, number, number]
  white?: number
  colorTemperature?: number
  coldWhite?: number
  warmWhite?: number
  transitionLength?: number
  flashLength?: number
  effect?: string
}

export interface LightState {
  isOn: boolean
  brightness: number
  colorMode: ColorMode
  colorBrightness: number
  red: number
  green: number
  blue: number
  white: number
  colorTemperature: number
  coldWhite: number
  warmWhite: number
  effect: string
}

export interface ServiceInfo {
  tyDomain: string
  subDomain?: string
  fullname: string
  server: string
  addresses: Array<string>
  port: number
  hostTtl: number
  otherTtl: number
  priority: number
  weight: number
}
