/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Light {
  key: number
  name: string
  kind: EntityKind.Light
  get isOn(): boolean
  get brightness(): number
  get colorMode(): ColorMode
  get colorBrightness(): number
  get rgb(): [number, number, number]
  get white(): number
  get colorTemperature(): number
  get coldWhite(): number
  get warmWhite(): number
  get effect(): string
  /**
   * Register a callback that is called whenever the light state changes.
   *
   * The callback receives a `LightState` object with all current state values.
   */
  onStateChange(callback: ((arg: LightState) => void)): void
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  toggle(): Promise<void>
  sendCommand(options: LightCommandOptions): Promise<void>
}

export declare class Manager {
  static connect(options: ConnectionOptions): Promise<Manager>
  getDeviceInfo(): DeviceInfo
  getEntities(): Array<Entity>
  /**
   * Subscribe to Home Assistant state events.
   *
   * Sends the subscription request to the device, then calls `callback` for every
   * subsequent event. The callback runs on the JS thread via a threadsafe function.
   *
   * Call this once per subscription; the callback keeps firing until the connection
   * closes. If you need a second independent listener, call
   * `onHomeAssistantState` instead (no extra request is sent).
   */
  subscribeHomeAssistantStates(callback: ((arg: HomeAssistantEvent) => void)): Promise<void>
  /**
   * Register an additional listener for Home Assistant state events without
   * sending a new subscription request to the device.
   *
   * Use this when `subscribe_home_assistant_states` has already been called
   * and you need a second independent callback.
   */
  onHomeAssistantState(callback: ((arg: HomeAssistantEvent) => void)): Promise<void>
  /**
   * Subscribe to Home Assistant action request events.
   *
   * Sends the subscription request to the device, then calls `callback` for every
   * subsequent action request. Call this once; use `onHomeAssistantActionRequest`
   * for additional listeners without re-sending the request.
   */
  subscribeHomeAssistantActionRequests(callback: ((arg: HomeassistantActionRequest) => void)): Promise<void>
  /**
   * Register an additional listener for Home Assistant action requests without
   * sending a new subscription request to the device.
   */
  onHomeAssistantActionRequest(callback: ((arg: HomeassistantActionRequest) => void)): Promise<void>
  /**
   * Subscribe to ESPHome logs.
   *
   * Sends the subscription request to the device, then calls `callback` for every
   * subsequent action request. Call this once; use `onLogs`
   * for additional listeners without re-sending the request.
   */
  subscribeLogs(level: LogLevel, dumpConfig: boolean, callback: ((arg: LogEvent) => void)): Promise<void>
  /**
   * Register an additional listener for ESPHome logs without
   * sending a new subscription request to the device.
   */
  onLogs(callback: ((arg: LogEvent) => void)): Promise<void>
  /**
   * Send the current state of a Home Assistant entity to the device.
   *
   * Used to respond to a `HomeAssistantEvent` of type `"StateSubscription"` or
   * `"StateRequest"`, or to push an update when a subscribed entity changes.
   */
  sendHomeAssistantState(entityId: string, state: string, attribute?: string | undefined | null): Promise<void>
  /**
   * Returns a Promise that resolves when the device initiates a disconnect.
   *
   * Use this to react to device restarts or OTA updates. The Manager is not
   * automatically reconnected; construct a new `Manager` to reconnect.
   *
   * ```ts
   * await Promise.race([manager.onDeviceDisconnect(), doWork(manager)])
   * ```
   */
  onDeviceDisconnect(): Promise<void>
  /**
   * Returns a Promise that resolves the next time the manager successfully
   * reconnects after a device-initiated disconnect.
   */
  onReconnect(): Promise<void>
  disconnect(): Promise<void>
}

export declare class Switch {
  key: number
  name: string
  kind: EntityKind.Switch
  get isOn(): boolean
  /**
   * Register a callback that is called whenever the switch state changes.
   *
   * The callback receives a single boolean argument indicating whether the switch is on.
   */
  onStateChange(callback: ((arg: boolean) => void)): void
  turnOn(): Promise<void>
  turnOff(): Promise<void>
  toggle(): Promise<void>
  setState(state: boolean): Promise<void>
}

export declare const enum ColorMode {
  Unknown = 0,
  OnOff = 1,
  LegacyBrightness = 2,
  Brightness = 3,
  White = 7,
  ColorTemperature = 11,
  ColdWarmWhite = 19,
  RGB = 35,
  RGBWhite = 39,
  RGBColorTemperature = 47,
  RGBColdWarmWhite = 51
}

export interface ConnectionOptions {
  address: string
  port: number
  password?: string
  expectedName?: string
  psk?: string
  clientInfo?: string
  keepAliveDuration?: number
}

export interface DeviceInfo {
  usesPassword: boolean
  name: string
  friendlyName: string
  macAddress: string
  compilationTime: string
  model: string
  manufacturer: string
  hasDeepSleep: boolean
  esphomeVersion: string
  projectName: string
  projectVersion: string
  webserverPort: number
  legacyVoiceAssistantVersion: number
  voiceAssistantFeatureFlags: number
  legacyBluetoothProxyVersion: number
  bluetoothProxyFeatureFlags: number
  suggestedArea: string
}

export declare function discover(seconds: number): Promise<Array<ServiceInfo>>

export type Entity =
  Light | Switch

export declare const enum EntityKind {
  Light = 'Light',
  Switch = 'Switch'
}

export interface HomeassistantActionRequest {
  service: string
  isEvent: boolean
  data: Record<string, string>
  dataTemplate: Record<string, string>
  variables: Record<string, string>
  callId: number
  wantsResponse: boolean
  responseTemplate: string
}

/**
 * A Home Assistant state event received from the ESPHome device.
 *
 * `eventType` is either `"StateSubscription"` (device wants ongoing updates)
 * or `"StateRequest"` (device wants the current value once).
 */
export interface HomeAssistantEvent {
  eventType: HomeAssistantEventKind
  entityId: string
  attribute?: string
}

export declare const enum HomeAssistantEventKind {
  StateSubscription = 'StateSubscription',
  StateRequest = 'StateRequest'
}

/**
 * Initialize the logger with a console-like object.
 * The object must have `debug`, `info`, `warn`, `error` and `trace` methods.
 *
 * Example:
 * ```javascript
 * initLogger(console);
 * ```
 */
export declare function initLogger(console: Pick<Console, 'warn' | 'error' | 'info' | 'debug' | 'trace'>): void

export interface LightCommandOptions {
  state?: boolean
  brightness?: number
  colorMode?: ColorMode
  colorBrightness?: number
  rgb?: [number, number, number]
  white?: number
  colorTemperature?: number
  coldWhite?: number
  warmWhite?: number
  transitionLength?: number
  flashLength?: number
  effect?: string
}

export interface LightState {
  isOn: boolean
  brightness: number
  colorMode: ColorMode
  colorBrightness: number
  red: number
  green: number
  blue: number
  white: number
  colorTemperature: number
  coldWhite: number
  warmWhite: number
  effect: string
}

export interface LogEvent {
  level: LogLevel
  message: string
}

export declare const enum LogLevel {
  None = 0,
  Error = 1,
  Warn = 2,
  Info = 3,
  Config = 4,
  Debug = 5,
  Verbose = 6,
  VeryVerbose = 7
}

export interface ServiceInfo {
  tyDomain: string
  subDomain?: string
  fullname: string
  server: string
  addresses: Array<string>
  port: number
}
