[package]
name = "esphomeapi-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
esphomeapi = { path = "../esphomeapi" }
tokio = { version = "1.45.0", features = [
  "net",
  "sync",
  "io-util",
  "rt-multi-thread",
  "macros",
  "signal",
] }
